[supervisord]
logfile=/root/gpufree-data/logs/gm-ai-supervisord.log
pidfile=/root/gpufree-data/gm-ai-supervisord.pid
childlogdir=/root/gpufree-data/logs
nodaemon=false
user=root

[include]
files=/root/gm-ai-server/supervisord/vlm-service.conf /root/gm-ai-server/supervisord/perception-service.conf
