[program:perception-service]
command=/root/gpufree-data/perception-service/start.sh
directory=/root/gpufree-data/perception-service
autostart=true
autorestart=true
startretries=20
startsecs=30
stopasgroup=true
killasgroup=true
stopsignal=TERM
stopwaitsecs=120
stdout_logfile=/root/gpufree-data/perception-service/supervisor.out.log
stderr_logfile=/root/gpufree-data/perception-service/supervisor.err.log
stdout_logfile_maxbytes=50MB
stdout_logfile_backups=3
priority=21
